export const CHARACTER_GET = "@CHARACTER_GET";
export const CHARACTER_GET_SUCCESS = "@CHARACTER_GET_SUCCESS";
export const CHARACTER_GET_FAILURE = "@CHARACTER_GET_FAILURE";

export const CHARACTER_GET_ALL = "@CHARACTER_GET_ALL";
export const CHARACTER_GET_ALL_SUCCESS = "@CHARACTER_GET_ALL_SUCCESS";
export const CHARACTER_GET_ALL_FAILURE = "@CHARACTER_GET_ALL_FAILURE";

export const FILTER_CHARACTERS = "@FILTER_CHARACTERS";


// eslint-disable-next-line
export default {
  CHARACTER_GET,
  CHARACTER_GET_SUCCESS,
  CHARACTER_GET_FAILURE,
  CHARACTER_GET_ALL,
  CHARACTER_GET_ALL_SUCCESS,
  CHARACTER_GET_ALL_FAILURE,
  FILTER_CHARACTERS,
};
